[common.consensus_config]
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[common.general_config]
validators_count = 4

[common.services_config]

[node]
addr = "127.0.0.1:6331"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "f668e7adfd0ae0f6c26b4c8f5c51b22f472a429aa1a860c45700ae658a82fd3a"
service_key = "a580d2bb0f5b0f95cf7cef41200b316c5949737fbce7b68d6573b00fe2df9eab"
